#!/bin/sh

MODE=$1
CODE1=$2
CODE2=$3

ADDR="FE.000000000007"

test -z "$MODE" -o -z "$CODE1" && {
  echo "go mode code1 [code2]"
  exit 1
}

test -z "$CODE2" && CODE2="0"

MODE=`expr "$MODE" + 1`
owwrite -s localhost:3000 /uncached/$ADDR/register1 $CODE1
owwrite -s localhost:3000 /uncached/$ADDR/register2 $CODE2
owwrite -s localhost:3000 /uncached/$ADDR/register0 $MODE


